### ISSUE TITLE
这行日志配置有个问题，类名中间插了四个看不见的空白，导致类名不正确

### ISSUE THREAD

**Issue by gdouzwt** [yangxiaobing175/contentManagerSystem#5]
https://github.com/yangxiaobing175/contentManagerSystem/blob/1fc8b1e13e48a99330fc58c46726d55ab0a5dd74/src/main/conf/dev/log4j2.xml#L5

`A‌​syncLoggerContextSel‌​ector` 这个是有问题的（肉眼看不出问题，复制粘贴到[TextMagic](https://www.textmagic.com/free-tools/unicode-detector)里就可以看到）

`AsyncLoggerContextSelector` 这个是正常的
看下面截图👇
![image](https://user-images.githubusercontent.com/7865168/85539296-403f1d00-b648-11ea-9237-af7fe2008d66.png)

很好奇怎么会写成这样:smile:

**Comment by yangxiaobing175** [comment]
已修改，我也很好奇😄
